import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'

declare global {
  interface FederatedModule {
    get: (path: string) => Promise<CallableFunction>
  }
  interface Window {
    contactApp: FederatedModule
  }
}

const RemoteContact = dynamic(() => {
  return window.contactApp?.get("./contact").then((factory) => factory())
}, {
  ssr: false
})

const ContactPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Host MFE | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RemoteContact />
    </>
  )
}

export default ContactPage
