import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'

import LoadingSpinner from '../../src/components/loading-spinner'
declare global {
  interface FederatedModule {
    get: (path: string) => Promise<CallableFunction>
  }
  interface Window {
    aboutApp: FederatedModule
  }
}

const RemoteAbout = dynamic(() => {
  return window.aboutApp?.get("./about").then((factory) => factory())
}, {
  ssr: false,
  loading: function loadingSpinner() {
    return <LoadingSpinner />
  }
})

const AboutPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Host MFE | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RemoteAbout />
    </>
  )
}

export default AboutPage
